[System.Environment]::SetenvironmentVariable("PYROSCOPE_APPLICATION_NAME","rideshare.dotnet.app",1)
[System.Environment]::SetenvironmentVariable("PYROSCOPE_SERVER_ADDRESS","http://localhost:8001",1)
[System.Environment]::SetenvironmentVariable("PYROSCOPE_PROFILING_ENABLED",1,1)
[System.Environment]::SetenvironmentVariable("CORECLR_ENABLE_PROFILING",1,1)
[System.Environment]::SetenvironmentVariable("CORECLR_PROFILER","{BD1A650D-AC5D-4896-B64F-D6FA25D6B26A}",1)
[System.Environment]::SetenvironmentVariable("CORECLR_PROFILER_PATH","Pyroscope.Profiler.Native.so",1)
[System.Environment]::SetenvironmentVariable("LD_PRELOAD","Pyroscope.Linux.ApiWrapper.x64.so",1)

[System.Environment]::SetenvironmentVariable("PYROSCOPE_APPLICATION_NAME",$null,1)
[System.Environment]::SetenvironmentVariable("PYROSCOPE_SERVER_ADDRESS",$null,1)
[System.Environment]::SetenvironmentVariable("PYROSCOPE_PROFILING_ENABLED",$null,1)
[System.Environment]::SetenvironmentVariable("CORECLR_ENABLE_PROFILING",$null,1)
[System.Environment]::SetenvironmentVariable("CORECLR_PROFILER",$null,1)
[System.Environment]::SetenvironmentVariable("CORECLR_PROFILER_PATH",$null,1)
[System.Environment]::SetenvironmentVariable("LD_PRELOAD",$null,1)
